sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dilshadcp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dilshadcp/docker-react npm run test