sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dilshadcp/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dilshadcp/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app:  "Docker-react-2"
  env: "dockerreact2-env"
  bucket_name: "elasticbeanstalk-us-east-2-513429949438"
  bucket_path:  "docker-react"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
